application: clouddevelopersgroup
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (README)|
 (readme\.txt)|
 (LICENSE)|
 (license\.txt)|
 (setup.py)
 )$